sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: "mvn -q clean install"
script: "mvn exec:exec "
before_install:
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
  - chmod +x .utility/push-javadoc-to-gh-pages.sh
  - chmod +x .utility/build-docs-site.sh
  - chmod +x .utility/maven-coveralls-hack.sh
  - chmod +x .utility/changelog-generator.sh
  - .utility/maven-coveralls-hack.sh
after_success:
  - .utility/changelog-generator.sh
  - .utility/push-javadoc-to-gh-pages.sh
  - cd geowave-test; mvn coveralls:report -Daccumulo.version=${ACCUMULO_VERSION} ${ACCUMULO_LEGACY} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -P ${PLATFORM_VERSION}

addons:
  apt_packages:
    - pandoc
  coverity_scan:
    project:
      name: ngageoint/geowave
      description: Build submitted via Travis CI
    notification_email: GeoWave@nga.mil
    build_command_prepend: mvn clean
    build_command: mvn clean compile -Dfindbugs.skip -Daccumulo.version=${ACCUMULO_VERSION} ${ACCUMULO_LEGACY}
      -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION}
      -DskipITs=true -DskipTests=true -P ${PLATFORM_VERSION}
    branch_pattern: coverity_scan